
version: "3"

services:
    app:
        # build:
        #     context: .
        depends_on:
            - php
        image: nginx:1
        ports:
            - "8080:80"
        volumes:
            - ./demo:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/html
    php:
        image: php:fpm
        volumes:
            - ./demo:/var/www/html
